### ISSUE TITLE
docker can't connect to amqp 

### ISSUE THREAD

**Issue by dfang** [subzerocloud/pg-amqp-bridge#14]
os: macOS high sierra  
postgres server and rabbitmq server run on localhost, pg-amqp-bridge run in docker

```
git checkout 0.0.6 
POSTGRESQL_URI="postgres://postgres:postgres@192.168.0.199:5432"  \
AMQP_URI="amqp://admin:admin@192.168.0.199//"  \ BRIDGE_CHANNELS="pgchannel1:task_queue,pgchannel2:direct_exchange,pgchannel3:topic_exchange" \
cargo run
```
works.

but 
```
  pg_amqp_bridge:
    image: subzerocloud/pg-amqp-bridge:0.0.6
    environment:
      - POSTGRESQL_URI=postgres://postgres:postgres@192.168.0.199:5432
      - AMQP_URI=amqp://admin:admin@192.168.0.199//
      - BRIDGE_CHANNELS=pgchannel1:task_queue,pgchannel2:direct_exchange,pgchannel3:topic_exchange
    restart: always

```

but docker-compose up got errors:
```
Attempting to obtain connection on AMQP server for pgchannel2 channel..
IoError(ConnectionRefused)
Retrying the AMQP connection for pgchannel2 channel in 1 seconds..
Attempting to obtain connection on AMQP server for pgchannel3 channel..
IoError(ConnectionRefused)
Retrying the AMQP connection for pgchannel3 channel in 1 seconds..
IoError(ConnectionRefused)
Retrying the AMQP connection for pgchannel1 channel in 2 seconds..
IoError(ConnectionRefused)
```
