### ISSUE TITLE
Postgres connection timeout in Docker Swarm

### ISSUE THREAD

**Issue by dargmuesli** [subzerocloud/pg-amqp-bridge#23]
I experienced no more responses from `pg-amqp-bridge` after 15 minutes or 900 seconds of `NOTIFY` inactivity. Having found https://github.com/moby/moby/issues/31208 I set the following setting on my PostgreSQL service in the `compose.yml`:

```yml
postgres:
    ...
    image: postgres:12.5-alpine@sha256:eee6f89fab183ebae62ad976722e3c2c1d201e73916af664d6c8fbfe9fe071fd
    ...
    sysctls:
      - net.ipv4.tcp_keepalive_time=600 # Prevent Docker Swarm from killing pg-amqp-bridge connections (https://github.com/moby/moby/issues/31208)
    ...
```

Just want to leave this here in case it helps someone else :)
